### ISSUE TITLE
testes no insomnia com as classes do LAPA

### ISSUE THREAD

**Issue by ines-alessandra** [lmtsufape/hvu#118]

**Comment by luisfelipe03** [comment]
Concentre-me inicialmente nos testes das classes do LAPA, mas, devido à relação com as classes do HVU, acabei testando todas as requisições e respostas. Todos os resultados foram conformes. Em seguida, realizei um reteste após remover bibliotecas não utilizadas (Issues#123), eliminando warnings. Esse processo otimizou o código, garantindo um ambiente estável e livre de alertas desnecessários.
