### ISSUE TITLE
Buscar vaga dado o id de agendamento

### ISSUE THREAD

**Issue by magnosillas** [lmtsufape/hvu#218]

**Comment by luisfelipe03** [comment]
![image](https://github.com/lmtsufape/hvu/assets/81371774/b66293fd-dc3e-4a53-9982-8128f32bc0ee)
![image](https://github.com/lmtsufape/hvu/assets/81371774/57dc054f-49f9-44ba-b138-c91169b38f62)
![image](https://github.com/lmtsufape/hvu/assets/81371774/f26e5e56-5955-4738-868f-bbb1c0a1d3b3)
![image](https://github.com/lmtsufape/hvu/assets/81371774/bdb1fc08-4b1f-4831-a147-b0ddc62c6b53)
