### ISSUE TITLE
Buscar vaga por especialidade

### ISSUE THREAD

**Issue by magnosillas** [lmtsufape/hvu#219]

**Comment by luisfelipe03** [comment]
![image](https://github.com/lmtsufape/hvu/assets/81371774/6fff1595-91f9-4f0e-a01f-19455018a566)
![image](https://github.com/lmtsufape/hvu/assets/81371774/5703ff2a-659f-4cbf-9966-3148dc6466a7)
![image](https://github.com/lmtsufape/hvu/assets/81371774/ecd3ca60-e33c-4fab-a91f-1309c6ac371b)
![image](https://github.com/lmtsufape/hvu/assets/81371774/62838935-ccf1-4b7a-b61e-23757822fab3)
